name: Compile the slide

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
  
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
            remote: true
    
      - name: Compile the matrix duck
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides-basics/matrixduck
          root_file: mduck.tex


      - name: Compile the basic slides
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides-basics
          root_file: |
            noanim_ltx_folien.tex
            ltx_folien.tex
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -e '$max_repeat=2'"

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f ./slides-basics/ltx_folien.pdf ./slides-basics/noanim_ltx_folien.pdf
          git commit -m "Update PDFs by Workflow"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}

