name: Compile the slide

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Install poppler utils
        run: |
          sudo apt install poppler-utils
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
            remote: true

      - name: Compile the matrix duck
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides-basics/matrixduck
          root_file: mduck.tex


      - name: Compile the basic slides
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides-basics
          root_file: |
            noanim_ltx_folien.tex
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -e '$max_repeat=2' -f"

      - name: Compile the advanced slides
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides-advanced
          root_file: |
              noanim_ltx_cmd_folien.tex
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -e  '$max_repeat=2' -f"
      - name: Generate previews
        run: |
          cp ./slides-basics/noanim_ltx_folien.pdf ./latex_folien.pdf
          cp ./slides-advanced/noanim_ltx_cmd_folien.pdf ./latex_2_folien.pdf
          pdftoppm -png -f 1 -l 1 ./latex_folien.pdf preview
          pdftoppm -png -f 1 -l 1 ./latex_2_folien.pdf preview_2
          ls
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f ./latex_folien.pdf ./latex_2_folien.pdf ./preview-1.png ./preview_2-1.png
          git commit -m "Update PDFs by Workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

